travis:
  secure:
    BINSTAR_TOKEN: UIgriAEyXeFZxLpjezRw2JUl2ZN1cDtf5u5iLUWa2TmzL3g1+LIHIC+CSsQ1VeyphRcjAd15xrEUcdUBAU1p8ZkpwTfpMiDxvJeHcZ8HzE/KKNyCWz8TXSHbZ/p7GzZ9BChW+dPKbTt1XlzaurDUIrDr1ht/pjexObtFkYflhStLavhVi8iOepc5hQtRaivfNckRX/T0fXduUQnP2OVnpIPpKfXIyol8syGAQQENas9f20ZKSoR+3A0ZTIrnWiV2LVq5KuLtAUJmyyQbHEJN+O1+5iwBUCpe3L5MXR4TxHm4ZCVoW1XUG7/fOr/ebtmxL0IJgOo5MZQODKWQftbE/ZOMQOqYSeknmxznuxvzjLEERav/Rh9n6sVU1whcDgPAJ7RvRey/Nprhn0AfbKmgvpWAuJ6huQPFjQMPs7xP7tyXjtYdHJ5uipioYCAQ5A+Yt0A/UwQEh796zrqEvqGw7COPqAGDM2nB9/cTXKX8/TXDC9/Soc4DLL0kEzNftOc9fwlpn+gh8ICp52oXQjGzHirI1JhFJriQ4S8Hbi9sv4rVhq7DvFFDoTHyQ1OBIXLdVeXwpg/+mlURCMOWD8JToGv8ibqrYzI8j2auuYHxPH4O2pMi3xKfG5k4upKz9s3X4VZfrIxuP048sOS9euZhqlvWo9QZg5aiA6TLCpekt00=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
